version: '3'
services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - 5001:5001
    healthcheck:
      test: exit 0
    command: ["sh", "entrypoint.sh"]
    volumes:
      - ".:/usr/src/"
    depends_on:
      - db
  db:
    image: postgres:10
    ports:
      - 5432:5432
    env_file:
      - .env
